# Generated by Django 5.1.7 on 2025-03-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes'), ('Books', 'Books'), ('Kitchen Appliances', 'Kitchen Appliances'), ('Home Decoration', 'Home Decoration')], max_length=50)),
            ],
        ),
    ]
