# Generated by Django 5.1.7 on 2025-03-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothes', 'Clothes'), ('Books', 'Books'), ('Kitchen Appliances', 'Kitchen Appliances'), ('Home Decoration', 'Home Decoration'), ('Makeup', 'Makeup'), ('Mobile', 'Mobile'), ('Hair care', 'Hair care')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
