# Generated by Django 5.1.7 on 2025-03-10 07:37

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0005_products_useful_for_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='useful_for_who',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Kids', 'Kids'), ('Women', 'Women'), ('Men', 'Men'), ('Night ware', 'Night ware'), ('Party ware', 'Party ware'), ('Novels', 'Novels'), ('Worksheets', 'Worksheets'), ('General', 'General'), ('Living room decoration', 'Living room decoration'), ('Home decor', 'Home decor'), ('Bathroom', 'Bathroom'), ('Bedroom', 'Bedroom'), ('Dining room', 'Dining room'), ('Study', 'Study'), ('Office', 'Office'), ('Garden', 'Garden'), ('Kitchen', 'Kitchen'), ('Lipstick', 'Lipstick'), ('Foundation', 'Foundation'), ('Skincare', 'Skincare'), ('Hair care', 'Hair care'), ('Fragrance', 'Fragrance'), ('Travel', 'Travel'), ('Personal care', 'Personal care'), ('Home care', 'Home care'), ('Nutrition', 'Nutrition'), ('Sports', 'Sports'), ('Pet care', 'Pet care')], max_length=259, null=True),
        ),
    ]
